server:
  port: 8010
spring:
  application:
    name: cloud-order-hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
logging:
  level:
    org.example.springcloud.service.PaymentHystrixService: debug
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true #在feign中开启hystrix
